### PR TITLE
metadata fixes

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by shirhatti** [comment]
Docs Build status updates of commit _[864167e](https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/25/commits/864167ee10b6c96940e44277bf1440e1a8d43e50)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-05374e22)

<a id="05374e22"></a>
###
 - **[Error]** `````Publishing of document 'IIS-Administration/api/iis.administration.swagger.json' failed at SafeOpenReadStream with relative path: IIS-Administration/api/iis.administration.swagger.json. Error: Could not find a part of the path 'E:\approot\build\%_op_cacheFolder%\IIS-Administration\hnxebanq.gso\432o0lw1.m45'.`````
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C3%5C93859af6-5ab6-bdbe-b7d9-68fc2e7930ed%5CPullRequest%5C201907030401012919-25%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lOe2DJDwOpHuSvDeoPxcbNnEC8eYA0vNXoqG7ba%2FCG0%3D&st=2019-07-03T03%3A57%3A18Z&se=2019-08-03T04%3A02%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by shirhatti — APPROVED** [review]

**Comment by shirhatti** [comment]
Good to merge?

**Comment by shirhatti** [comment]
Docs Build status updates of commit _[864167e](https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/25/commits/864167ee10b6c96940e44277bf1440e1a8d43e50)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[IIS-Administration/api/files.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/files.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/api/files?branch=pr-en-us-25) | [Details](#user-content-40fd3d40-4ec19960)
[IIS-Administration/api/installing-features.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/installing-features.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/api/installing-features?branch=pr-en-us-25) | [Details](#user-content-b8e4e3b1-4ec19960)
[IIS-Administration/api/request-tracing.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/request-tracing.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/api/request-tracing?branch=pr-en-us-25) | [Details](#user-content-98bb1544-4ec19960)
[IIS-Administration/api/scope.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/scope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/api/scope?branch=pr-en-us-25) | [Details](#user-content-07e9c8b9-4ec19960)
[IIS-Administration/api/sites.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/sites.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/api/sites?branch=pr-en-us-25) | [Details](#user-content-f326d717-4ec19960)
[IIS-Administration/configuration/appsettings.json.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/configuration/appsettings.json.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/configuration/appsettings.json?branch=pr-en-us-25) | [Details](#user-content-e56f4e66-4ec19960)
[IIS-Administration/index.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/index.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/index?branch=pr-en-us-25) | [Details](#user-content-e5105a9d-4ec19960)
[IIS-Administration/security/access-tokens.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/security/access-tokens.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/security/access-tokens?branch=pr-en-us-25) | [Details](#user-content-df6444b0-4ec19960)
[IIS-Administration/security/integrated/authorization.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/security/integrated/authorization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/IIS-Administration/security/integrated/authorization?branch=pr-en-us-25) | [Details](#user-content-cae9e0f4-4ec19960)
[IIS-Administration/docfx.json](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/docfx.json) | :white_check_mark:Succeeded | |

<a id="40fd3d40-4ec19960"></a>
### [IIS-Administration/api/files.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/files.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="b8e4e3b1-4ec19960"></a>
### [IIS-Administration/api/installing-features.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/installing-features.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="98bb1544-4ec19960"></a>
### [IIS-Administration/api/request-tracing.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/request-tracing.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="07e9c8b9-4ec19960"></a>
### [IIS-Administration/api/scope.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/scope.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="f326d717-4ec19960"></a>
### [IIS-Administration/api/sites.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/api/sites.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="e56f4e66-4ec19960"></a>
### [IIS-Administration/configuration/appsettings.json.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/configuration/appsettings.json.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="e5105a9d-4ec19960"></a>
### [IIS-Administration/index.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/index.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="df6444b0-4ec19960"></a>
### [IIS-Administration/security/access-tokens.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/security/access-tokens.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="cae9e0f4-4ec19960"></a>
### [IIS-Administration/security/integrated/authorization.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/metadata/IIS-Administration/security/integrated/authorization.md)
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C26%5C93859af6-5ab6-bdbe-b7d9-68fc2e7930ed%5CPullRequest%5C201907260035586333-25%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hJhYLlkXkpXvZe8EzK3wpD0DtUjYBWr%2Fm8ArQ8vHSGk%3D&st=2019-07-26T00%3A32%3A16Z&se=2019-08-26T00%3A37%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
The bug was fixed and now my PR passed. It seems that there are some other metadata issues that we need to fix here.

**Pull request merged**
