### PR TITLE
Change markdown parser

### PR DESCRIPTION
**Pull request by shirhatti**

### CODE REVIEW

**Comment by shirhatti** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 16**: **[Error]** Restore nuget package W:\kyph-s\.optemp\packages\opbuild.scripts.1.46.2\tools\packages.config in folder:W:\kyph-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;2.32.1&#39; of package &#39;docfx.console&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;docfx.console.2.32.1&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://www.myget.org/F/op/api/v2/: Package &#39;docfx.console.2.32.1&#39; is not found on source &#39;https://www.myget.org/F/op/api/v2/&#39;.       https://nuget.org/api/v2/: Package &#39;docfx.console.2.32.1&#39; is not found on source &#39;https://nuget.org/api/v2/&#39;.       https://www.myget.org/F/docfx-dev/api/v2/: Package &#39;docfx.console.2.32.1&#39; is not found on source &#39;https://www.myget.org/F/docfx-dev/api/v2/&#39;.       https://www.myget.org/F/op-dev/api/v2/: Package &#39;docfx.console.2.32.1&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2/&#39;.       https://www.myget.org/F/docfx/api/v2/: Package &#39;docfx.console.2.32.1&#39; is not found on source &#39;https://www.myget.org/F/docfx/api/v2/&#39;.     Unable to find version &#39;1.46.2&#39; of package &#39;opbuild.initializecrrtool&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;opbuild.initializecrrtool.1.46.2&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://nuget.org/api/v2/: Package &#39;opbuild.initializecrrtool.1.46.2&#39; is not found on source &#39;https://nuget.org/api/v2/&#39;.       https://www.myget.org/F/op/api/v2/: Package &#39;opbuild.initializecrrtool.1.46.2&#39; is not found on source &#39;https://www.myget.org/F/op/api/v2/&#39;.       https://www.myget.org/F/op-dev/api/v2/: Package &#39;opbuild.initializecrrtool.1.46.2&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2/&#39;.       https://www.myget.org/F/docfx-dev/api/v2/: Package &#39;opbuild.initializecrrtool.1.46.2&#39; is not found on source &#39;https://www.myget.org/F/docfx-dev/api/v2/&#39;.       https://www.myget.org/F/docfx/api/v2/: Package &#39;opbuild.initializecrrtool.1.46.2&#39; is not found on source &#39;https://www.myget.org/F/docfx/api/v2/&#39;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C93859af6-5ab6-bdbe-b7d9-68fc2e7930ed%5CPullRequest%5C201806271920420024-11%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=svbGhzjDUaHZQOyhtoLNfRjbCx1wUnmDrpfAtr7pvWo%3D&st=2018-06-27T19%3A16%3A10Z&se=2018-07-28T19%3A21%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by shirhatti** [comment]
@cillroy Still seeing this issue

**Comment by cillroy** [comment]
Did the issue ever resolve itself?  Did you try a fresh PR?

**Comment by shirhatti** [comment]
It was a transient issue in https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/10
And now it's happening again here

**Comment by daxianji007** [comment]
Confirmed with OP team. This is a known issue and not related to markdig migration. Please trigger a force build for live branch, then re-open the PR. The issue will be resolved.

**Comment by shirhatti** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[IIS-Administration/api/certificates.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/master/IIS-Administration/api/certificates.md) | :white_check_mark:Succeeded | |
[IIS-Administration/api/scope.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/master/IIS-Administration/api/scope.md) | :white_check_mark:Succeeded | |
[IIS-Administration/configuration/appsettings.json.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/master/IIS-Administration/configuration/appsettings.json.md) | :white_check_mark:Succeeded | |
[IIS-Administration/docfx.json](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/master/IIS-Administration/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C25%5C93859af6-5ab6-bdbe-b7d9-68fc2e7930ed%5CPullRequest%5C201808250058022401-11%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZS2TcpIx7fjSgW3sApEE4GyJzAVT1iTLIuLePDYjtc4%3D&st=2018-08-25T00%3A55%3A26Z&se=2018-09-25T01%3A00%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
