### PR TITLE
add titles and descriptions

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by shirhatti** [comment]
OPS Build status updates of commit _[d990618](https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/17/commits/d990618f34b4f37550bce8da3bc60f83cd5d641f)_: 

:clock10: **Preparing**: average preparing time is _32 sec(s)_

**Comment by shirhatti** [comment]
OPS Build status updates of commit _[d990618](https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/17/commits/d990618f34b4f37550bce8da3bc60f83cd5d641f)_: 

:clock10: **Incremental building**: average incremental building time is not available, there is no data for this repository.

**Comment by shirhatti** [comment]
OPS Build status updates of commit _[d990618](https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/17/commits/d990618f34b4f37550bce8da3bc60f83cd5d641f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[IIS-Administration/api/api-keys.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/title/ra/IIS-Administration/api/api-keys.md) | :white_check_mark:Succeeded | |
[IIS-Administration/api/applications.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/title/ra/IIS-Administration/api/applications.md) | :white_check_mark:Succeeded | |
[IIS-Administration/api/certificates.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/title/ra/IIS-Administration/api/certificates.md) | :white_check_mark:Succeeded | |
[IIS-Administration/getting-started.md](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/title/ra/IIS-Administration/getting-started.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C25%5C93859af6-5ab6-bdbe-b7d9-68fc2e7930ed%5CPullRequest%5C201901250111269938-17%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eT8RznTtzUR5m6o9PcmnmxJv%2B%2BrpkbC9U%2BcvENh2%2Bh0%3D&st=2019-01-25T01%3A08%3A04Z&se=2019-02-25T01%3A13%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by mairaw — APPROVED** [review]

**Comment by mairaw** [comment]
Can we get this reviewed and merged @shirhatti?

**Review by shirhatti — APPROVED** [review]

**Pull request merged**
