### PR TITLE
New build pipeline will not support build swagger.json

### PR DESCRIPTION
**Pull request by yishengjin1413**
@mairaw @jimmyca15 
Is this page still needed? https://docs.microsoft.com/en-us/IIS-Administration/api/iis.administration

We will not support build [swagger.json](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/live/IIS-Administration/api/iis.administration.swagger.json) in our V3 build pipeline. If this page is not needed now, please help to approve this PR.

If this page is needed, we have two options and please let me know which one do you prefer:

1. Revert the build pipeline to V2, the impact is that OPS build will about 10 times slower than V3. 
2. Use our current rest pipeline to transfer this [swagger.json](https://github.com/MicrosoftDocs/IIS.Administration-docs/blob/live/IIS-Administration/api/iis.administration.swagger.json) to multiple yaml files, each file will just contains operation and the page will look like this one: https://docs.microsoft.com/en-us/rest/api/netapp/netappresource/checkfilepathavailability?branch=master. The impact is that you may need to create an onboard request [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR958mqNUZExPsLDhzSGD8aFUOVNBNTZOMVlXRFFOMEU1UTNDOE84M09SNS4u) and you can also refer to [this topic](https://review.docs.microsoft.com/en-us/help/onboard/rest-requirements?branch=master). 

Let me know if you have any questions.

cc @live1206

### CODE REVIEW

**Comment by mairaw** [comment]
This would be a question for @shirhatti

**Comment by yishengjin1413** [comment]
@shirhatti Kindly ping. Would you help to have a check about this PR?

cc @live1206

**Comment by mairaw** [comment]
@shirhatti I see that new PRs are now failing. Can you review this?

**Comment by shirhatti** [comment]
Can we do a manual migration of content? This content updates extremely infrequently

**Comment by shirhatti** [comment]
Given how infrequently this content updates, I'd rather have a failing build and lose the ability to update than yank out existing content that is still valid.

**Comment by mairaw** [comment]
I think staying in V2 might be ok for you given it doesn't update that often. That way you could continue to use as-is if I understood correctly.

**Comment by shirhatti** [comment]
Can I close this PR then?

**Comment by mairaw** [comment]
I think this PR might need to be changed to roll back the engine to V2? I see all new PRs are failing. @yishengjin1413?

**Pull request closed without merging**
